linters:
  enable:
    - gosec
    - misspell
    - sqlclosecheck
    - errorlint
    - exhaustive
    - gocritic
    - sloglint
    - noctx
    - perfsprint

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G204 # iSubprocess launched with a potential tainted input or cmd arguments

issues:
  exclude-rules:
    - path: _test.go
      text: ".*"
