watch: true

servers:
  api_server:
    bind: "127.0.0.1:8001"

routes:
  all_routes:
    paths:
      - /
    service_id: test_service

services:
  test_service:
    url: "http://test_upstream:8000"

upstreams:
  test_upstream:
    targets:
      - target: "127.0.0.1:8000"
