apiVersion: v1
kind: Service
metadata:
  labels:
    app: bifrost
  name: bifrost
spec:
  ports:
    - name: 80-80
      nodePort: 30080
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: bifrost
  type: NodePort
