---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bifrost-config
data:
  config.yaml: |
    watch: true

    providers:
      k8s:
        enabled: true

    logging:
      handler: text
      level: error
      output: /logs/error.log
      redirect_stderr: false

    servers:
      apiv1:
        bind: ":8001"

    routes:
      default:
        paths:
          - /
        service_id: api

    services:
      api:
        tls_verify: false
        protocol: http
        url: http://httpServer

    upstreams:
      httpServer:
        discovery:
          type: "k8s"
          name: "echo"
          namespace: "default"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bifrost-deployment
  labels:
    app: bifrost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bifrost
  template:
    metadata:
      labels:
        app: bifrost
    spec:
      containers:
        - name: bifrost
          image: jasonsoft/bifrost:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: bifrost-config
